server:
  port: 8761

eureka:
  instance:
    hostname: eureka-rgallagher.cfapps.pez.pivotal.io
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/